#!/bin/bash
# Handy bash script that prints your terminal's colours.

for i in {0..255} ; do
printf "\x1b[48;5;%sm%3d\e[0m " "$i" "$i"
done
if (( i == 15 )) || (( i > 15 )) && (( (i-15) % 6 == 0 )); then
    printf "\n";
fi

